In [84]:
# Downloaded the data as an Excel file from Analytics dashboard: https://datastudio.google.com/u/0/reporting/1jGAALdF8Mx3e3RxvkHyEUE5Iju0tY2j2/page/RXJQB
# Saved all the data as text (copied it into notepad and then pasted it back in using Text Import Wizard)
# Renamed the sheetname as "Searched Terms" and the file location is "C:\Users\satal\Desktop\Internship\UK Trade Tariffs_Page Views and Searches Table.xlsx"

"""
Import Excel
"""

import pandas as pd 

ExcelRead = pd.read_excel(r"C:\Users\satal\Desktop\Internship\UK Trade Tariffs_Page Views and Searches Table.xlsx", sheet_name = "Searched Terms")

print(ExcelRead)

                      Search Term  Unique Searches
0                          850110            457.0
1                         7108095            420.0
2                          cheese            398.0
3                         bicycle            324.0
4                           sugar            279.0
5                     liberalised            257.0
6                          engine            209.0
7                       champagne            209.0
8                        20021090            189.0
9                        20097919            175.0
10                              2            169.0
11                       19021100            163.0
12                       16041600            161.0
13                       19019095            155.0
14                           2204            152.0
15                           2309            150.0
16                           Wine            146.0
17                         sowing            145.0
18                       19023010            142.0
19                           8543            129.0
20                       21069098            128.0
21                          70410            126.0
22                       bicycles            115.0
23                           1806            113.0
24                           1001            112.0
25                       20079997            111.0
26                              0            110.0
27                           1602            108.0
28                            207            107.0
29                       20041010            106.0
...                           ...              ...
13118  other articles of plastics              1.0
13119             Kitchencabinets              1.0
13120                     3923109              1.0
13121                    lecithin              1.0
13122                  Door handl              1.0
13123                      200981              1.0
13124                    Rapeseed              1.0
13125                      cotton              1.0
13126                      Valves              1.0
13127                    84145935              1.0
13128                    61044200              1.0
13129                   flower bu              1.0
13130                    85423990              1.0
13131                  3502 2091               1.0
13132                Hockey stick              1.0
13133                    Cherries              1.0
13134             Packing machine              1.0
13135                    22083088              1.0
13136                    85445910              1.0
13137                    87084099              1.0
13138                 Hand tools               1.0
13139                  furnitures              1.0
13140                   Classicar              1.0
13141          Tinned baked beans              1.0
13142                    32089090              1.0
13143                     3021400              1.0
13144                  3301 90 90              1.0
13145                      151000              1.0
13146                maize gluten              1.0
13147           flexible material              1.0

[13148 rows x 2 columns]

In [85]:
#retrieved JSON file from data.jason from uktrade/global-uk-tariff (github)
#uploaded JSON file to python using json.load

import json

with open('/Users/satal/Desktop/Internship/data.json') as data_file:
        data = json.load(data_file)
        
for code in data:
    code["total"] = 0

print(data[0])

{'commodity': '01012100', 'description': 'Pure-bred breeding horses', 'cet_duty_rate': '0.0%', 'ukgt_duty_rate': '0.0%', 'change': 'No change', 'trade_remedy_applies': False, 'cet_applies_until_trade_remedy_transition_reviews_concluded': False, 'suspension_applies': False, 'atq_applies': False, 'total': 0}

In [86]:
ExcelRead

                      Search Term  Unique Searches
0                          850110            457.0
1                         7108095            420.0
2                          cheese            398.0
3                         bicycle            324.0
4                           sugar            279.0
5                     liberalised            257.0
6                          engine            209.0
7                       champagne            209.0
8                        20021090            189.0
9                        20097919            175.0
10                              2            169.0
11                       19021100            163.0
12                       16041600            161.0
13                       19019095            155.0
14                           2204            152.0
15                           2309            150.0
16                           Wine            146.0
17                         sowing            145.0
18                       19023010            142.0
19                           8543            129.0
20                       21069098            128.0
21                          70410            126.0
22                       bicycles            115.0
23                           1806            113.0
24                           1001            112.0
25                       20079997            111.0
26                              0            110.0
27                           1602            108.0
28                            207            107.0
29                       20041010            106.0
...                           ...              ...
13118  other articles of plastics              1.0
13119             Kitchencabinets              1.0
13120                     3923109              1.0
13121                    lecithin              1.0
13122                  Door handl              1.0
13123                      200981              1.0
13124                    Rapeseed              1.0
13125                      cotton              1.0
13126                      Valves              1.0
13127                    84145935              1.0
13128                    61044200              1.0
13129                   flower bu              1.0
13130                    85423990              1.0
13131                  3502 2091               1.0
13132                Hockey stick              1.0
13133                    Cherries              1.0
13134             Packing machine              1.0
13135                    22083088              1.0
13136                    85445910              1.0
13137                    87084099              1.0
13138                 Hand tools               1.0
13139                  furnitures              1.0
13140                   Classicar              1.0
13141          Tinned baked beans              1.0
13142                    32089090              1.0
13143                     3021400              1.0
13144                  3301 90 90              1.0
13145                      151000              1.0
13146                maize gluten              1.0
13147           flexible material              1.0

[13148 rows x 2 columns]

In [87]:
# matches everything in the searched terms list to all the possibile commodity codes it could match to
# you can double check this code works by using the UKGT tool: https://www.check-future-uk-trade-tariffs.service.gov.uk/tariff
# the code also counts the matches. For example, if 17028937 is the comm code for 'vegtables', and 17028937 has been searched for 50 times while 'vegetables' has been searched for 20 times. Then the total search for 17028937 is 70. 

for row in ExcelRead.itertuples():
    index, term, count = row
    #if index>500:
      #  break
   # print (term)
    for code in data:
        match = term in code["commodity"] or term.lower() in code["description"].lower() or term.lower() in code["change"].lower()
        if match :
            code["total"] += count

In [88]:
#max(data, key = lambda code : code["total"])

#sorts and gives the top 10 most searched terms

top_searches=sorted(data, key = lambda code : code["total"])[-10:]

#print(top_searches)

#saved the top 10 searches as a JSON file so that we can start representing the data as diagrams using Excel

with open ('top_searches.json','w') as f:
    json.dump(top_searches, f, indent=2)

In [90]:
top_100=sorted(data, key = lambda code : code["total"])[-100:]

with open ('top_100.json','w') as p:
    json.dump(top_100, p, indent=2)